# Длины полей
MAX_PROJECT_NAME_LENGTH = 200
MAX_STATUS_LENGTH = 6
MAX_PHONE_LENGTH = 12
MAX_SKILL_NAME_LENGTH = 124
MAX_USER_NAME_LENGTH = 124
MAX_USER_SURNAME_LENGTH = 124
MAX_USER_ABOUT_LENGTH = 256

# Статусы проектов
STATUS_OPEN = "open"
STATUS_CLOSED = "closed"

# Пагинация
PAGE_SIZE = 12
AUTOCOMPLETE_LIMIT = 10

# Валидация
PHONE_REGEX = r"^\+7\d{10}$"
GITHUB_DOMAIN = "github.com"

# Аватары
AVATAR_SIZE = (200, 200)
AVATAR_FONT_SIZE = 100
AVATAR_TEXT_COLOR = (255, 255, 255)
